package com.example.wallet.Api;

public class Transaction {
    public int id;
    public int userId;
    public int standardId;
    public String date;
    public String dueDate;
    public Object paymentDate;
    public Object refundDate;
    public Object transferDate;
    public Object paymentId;
    public String amount;
    public double transactionFee;
    public double settlementFee;
    public double amountPayable;
    public double processignPaidByIns;
    public String org;
    public String orgId;
    public String orgName;
    public Object payment_method;
    public Object attempt;
    public String status;
    public Object trnsDetails;
    public String receipt;
    public Object callback;
    public String note;
    public String linkSentBy;
    public Object refundedBy;
    public Object transferedBy;
    public String transactionPaidBy;
    public String gst;
    public boolean gstApplicable;
    public String discount_details;
    public String addition_details;
    public float total_discount;
    public float total_addition;
    public String payment_type;
    public String cheque_no;
    public User user;
}
